### PR TITLE
201 earthdata dh

### PR DESCRIPTION
**Pull request by bhbraswell**
#201 earthdata auth now handled in a sort of generic way by adding a class method called "managed_auth" into the Repository class.

This is implemented for modis and merra in this branch.

This removes the requirement of ~/.netrc for these drivers

Other earthdata drivers (whatever they are) will still work if there is a ~/.netrc

### CODE REVIEW

**Comment by ags-tolson** [comment]
Temporarily closing because something funny is going on with this branch; need a minute to sort it out.

**Comment by ags-tolson** [comment]
So this PR is two things at once, which is why I was confused:  it's both merging dev into b-s, and also adding new commits for a new feature.  Normally we do that separately for a few reasons.  One good reason:  Presumably dev wants the auth changes as much as b-s does, and if you do it the normal way you get both.  Here's how to do it the normal way starting from this point:

1. port the new commits onto a new branch off of dev (with cherry pick or rebase)
2. issue a PR to merge that new branch into dev
3. issue a new PR to merge dev into b-s

If someone wants to re-open this, they are of course welcome to!  It's something we'd probably get away with, in this case, but not necessarily a good practice.  We'd still be missing auth fixes in dev, though, and I can't remember how soon b-s is expected to merge back into dev.

**Comment by bhbraswell** [comment]
@ircwaves I defer to you. I can start over if you want.

**Comment by ags-tolson** [comment]
If all the commits are present already, there's no need to start over; just re-use the existing commits with one of the git tools for the purpose; there's so few commits that cherry-pick is probably sufficient:

https://git-scm.com/docs/git-cherry-pick

I defer too, though; either way.

**Comment by ircwaves** [comment]
I propose merging dev into batch-scheduler, as has been our regular
practice, and then I believe this PR will fix itself.

**Comment by bhbraswell** [comment]
> I propose merging dev into batch-scheduler, as has been our regular practice, and then I believe this 
PR will fix itself.

Should this PR remained closed until then?

**Pull request closed without merging**
