### PR TITLE
142 merra

### PR DESCRIPTION
**Pull request by ircwaves**
tests pass in venv on my laptop....what say you @agsjenkins

### CODE REVIEW

**Comment by ircwaves** [comment]
ok.  tweaked test invocation to be only merra, and to spit out some info because the `pytest_results.xml is not being copied out of the test container. [mic check]

**Comment by ags-tolson** [comment]
is any of this branch being reviewed already, or should I review the whole thing?  I ask because there are two committers and you could be reviewing eachother's stuff maybe, don't want to duplicate work.

**Comment by ircwaves** [comment]
I think we should make a practice of requesting a review when it is ready for such.  This isn't at review point yet.  Thanks for checking.

**Comment by ircwaves** [comment]
[mic check] -- moved the `copy xml from container` to another build task within jenksins job

**Comment by justinfisk** [comment]
re-opening to use for further CI testing

**Pull request merged**
