### PR TITLE
147 raise when asset found in FS unexpectedly

### PR DESCRIPTION
**Pull request by ags-tolson**
If the file exists in the filesystem, but not in the DB inventory, that's a bad state that should only happen in very strange circumstances.  So, it's okay to raise an exception and give up provided the error message is sensible.

### CODE REVIEW

**Comment by justinfisk** [comment]
Unfortunately, I don't think this case is as odd or rare as perhaps it should be. Several of us sometimes point to the same large archive (using separate DBs) for testing things without inducing onerous fetch requirements. 

I think it would be better to mark as complete and log a note about it. Otherwise DH jobs get stuck and require manual intervention to get going again. 

In general, I think the DH should be as self-recovering as possible. It is possible that this would introduce an incomplete file to the DB inventory, but that will be solved when we fully implement good temp dirs.

**Comment by ags-tolson** [comment]
I think it's easy to put in a self-healing line instead of the raise; I think it's a one-liner, something like `asset.archived_filename = newfilename` where the raise currently is.  I agree with you too, self-healing is best.

Can I tell you one concern before I do that?  I think there's enough to do here for self-healing that I kinda think we should leave it as the raise for now.  I worry that blessing an unexpected file, in the operational case, may be inserting random erroneous data into the archive rather than curing the ignorance of the database.  It seems like the really safe play is to bless the staged file that we're trying to archive, while the mystery file should be placed in the quarantine.

However, I can still add that line for now and we can implement fancier remediation later if you'd rather.

**Comment by justinfisk** [comment]
I agree that using the file that was just downloaded and quarantining the mystery file sounds safer/better.

**Comment by ircwaves** [comment]
Per discussion:
+ quarantine the existing asset
+ archive the freshly downloaded asset.

**Comment by ags-tolson** [comment]
Self-healing is ready for code review

**Pull request merged**
