### PR TITLE
70 delete objects to cover for GDAL<2 faults

### PR DESCRIPTION
**Pull request by ags-tolson**
this is take 2 of #184

### CODE REVIEW

**Comment by bhbraswell** [comment]
Possibly my misunderstanding but I thought this would take the form of:
```
img = gippy.GeoImage([whatever])
...process code stuff...
...all done with this block...
img = None # or del img
```

**Comment by ags-tolson** [comment]
@bhbraswell that's what I was going for; is there a section that doesn't look right?

**Comment by ircwaves** [comment]
@bhbraswell -- it seems to be approximately that...maybe more:
```python
img = GeoImage(fname)
... blah blah ...
del img
... do one more thing in the block ...
```
Might be more visually clear to have it be the last action of the if-block.  Otherwise, this is fine -- provided that this passes the modis system tests AND doesn't choke on a HDF subdataset.

@ags-tolson -- are the two caveats above satisfied?

**Comment by ags-tolson** [comment]
It passed the system tests and the unit tests.  I'm not sure about the other condition . . . how would I check that?

**Comment by ircwaves** [comment]
The other condition is just that the original NDVI8 bug (AKA too many products) no longer manifests.   I don't know if that showed itself in the system tests.

**Comment by ags-tolson** [comment]
Here's the (manual) process I used.  I ran this command on the unchanged dev branch:

`gips_process modis -s gips/test/NHseacoast.shp -d 2012-01-09,2012-01-09 -v 4`

Then I ran it again with the fix in place.  The former broke while the latter worked.

The bug never showed in the system tests, though, because those tests used a trio of dates (336-338 in 2012) that didn't have enough products in them to cause the problem.

**Comment by ircwaves** [comment]
I believe that satisfies the second caveat.

**Pull request merged**
