### PR TITLE
Proto cleanup 1 of ?

### PR DESCRIPTION
**Pull request by ags-tolson**
this fixes the concurrency problem I rediscovered the other day.  Also a few random cleanup items to move it towards production quality.

### CODE REVIEW

**Comment by ircwaves** [comment]
@ags-tolson -- unfortunately, this PR got conflicted on the vine.

  Can you resolve the conflicts, or have the relevant fixes made their way i via other routes?

**Comment by ags-tolson** [comment]
I think there're enough incoming changes to the relevant parts of the code that this PR may be no longer worth the trouble . . . I'd probably start fresh and go through the diff, picking out the changes that matter the most (probably ignoring, for instance, the automated tests).

**Comment by ircwaves** [comment]
Given that, I'll close this one just to *try* to keep things tidy.

**Comment by ags-tolson** [comment]
:+1:

**Pull request closed without merging**
