### PR TITLE
Fix for #44, add support for modis collection 6 (and retain support for 5)

### PR DESCRIPTION
**Pull request by ags-tolson**
This was made by:  `git checkout modis-6 && git rebase -i master HEAD --onto dev`

The diff doesn't look exactly the same as the old PR:

https://github.com/Applied-GeoSolutions/gips/pull/53

@bhbraswell could you read through this and confirm that it looks right?  If there are any problems we can add commits until it's okay.  Likewise I would like to add unit tests.  I also want to confirm system tests still pass, but for that I have to wait on other PRs.

### CODE REVIEW

**Comment by bhbraswell** [comment]
Except for the print statement it looks ok to me.

We can talk about tests. I tested gips_process with:
- no asset present, update not set —> you get a v6 asset
- no asset present, update set —> you get a v6 asset
- v5 asset present, update not set —> nothing happens
- v5 asset present, update set —> you get a v6 asset
- v6 asset present, update not set —> nothing happens
- v6 asset present, update set —> nothing happens*

* if the version string evaluates to a larger number in the downloaded data, then it will replace the current asset. I think this is possible.

**Comment by ags-tolson** [comment]
So the system tests need revision to pass, for obvious reasons:  Source data changes result in process & project data changes.  I want to double-check what I'm seeing in these test runs so I'm going to post outcomes here and I'd like to get feedback.

To start with, here's what had to change to make the test of `gips_inventory --fetch` pass again; what it's running that gets these files is effectively `gips_inventory modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-01 -v 4 --fetch`

```
+        'modis/tiles/h12v04/2012336/MCD43A2.A2012336.h12v04.006.2016112010833.hdf': 531008224,
+        'modis/tiles/h12v04/2012336/MCD43A4.A2012336.h12v04.006.2016112010833.hdf': -955061246,
         'modis/tiles/h12v04/2012336/MOD10A1.A2012336.h12v04.005.2012339213007.hdf': 1588268768,
         'modis/tiles/h12v04/2012336/MOD11A1.A2012336.h12v04.005.2012339180517.hdf': -868909291,
         'modis/tiles/h12v04/2012336/MYD10A1.A2012336.h12v04.005.2012340031954.hdf': 1810195064,
```

**Comment by ags-tolson** [comment]
Here're the change that makes the system test for `gips_process` work.  I'm nervous about some of these lines as it looks like certain products are lost for 2012-338.  Command line:  `gips_process modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-03 -v 4`

Here's the changes to the list of created files:
```
     'created': {
         # TODO Are these broken or what?  Each None is a broken symlink:
         # See https://github.com/Applied-GeoSolutions/gips/issues/54
+        'modis/tiles/h12v04/2012336/h12v04_2012336_MCD_quality.tif': None,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MCD_quality.tif': None,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MOD_temp8td.tif': None,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MOD_temp8tn.tif': None,
+        'modis/tiles/h12v04/2012336/MCD43A2.A2012336.h12v04.006.2016112010833.hdf.index': 1818315139,
+        'modis/tiles/h12v04/2012336/MCD43A4.A2012336.h12v04.006.2016112010833.hdf.index': 502383905,
         'modis/tiles/h12v04/2012336/MOD10A1.A2012336.h12v04.005.2012339213007.hdf.index': -1075525670,
         'modis/tiles/h12v04/2012336/MOD11A1.A2012336.h12v04.005.2012339180517.hdf.index': -1602319177,
         'modis/tiles/h12v04/2012336/MYD10A1.A2012336.h12v04.005.2012340031954.hdf.index': 1623945316,
         'modis/tiles/h12v04/2012336/MYD11A1.A2012336.h12v04.005.2012341040543.hdf.index': -1720582124,
         'modis/tiles/h12v04/2012336/h12v04_2012336_MCD_fsnow.tif': -843500181,
+        'modis/tiles/h12v04/2012336/h12v04_2012336_MCD_indices.tif': -1977616018,
         'modis/tiles/h12v04/2012336/h12v04_2012336_MCD_snow.tif': 388495321,
         'modis/tiles/h12v04/2012336/h12v04_2012336_MOD-MYD_obstime.tif': 1994827924,
         'modis/tiles/h12v04/2012336/h12v04_2012336_MOD-MYD_temp.tif': 2094570047,
         'modis/tiles/h12v04/2012336/h12v04_2012336_MOD_clouds.tif': 161070470,
-        'modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.005.2012356160504.hdf.index': 1869798455,
-        'modis/tiles/h12v04/2012337/MCD43A4.A2012337.h12v04.005.2012356160504.hdf.index': 1702701995,
+        'modis/tiles/h12v04/2012337/MCD43A2.A2012337.h12v04.006.2016112013509.hdf.index': 335987188,
+        'modis/tiles/h12v04/2012337/MCD43A4.A2012337.h12v04.006.2016112013509.hdf.index': -1583910758,
         'modis/tiles/h12v04/2012337/MOD09Q1.A2012337.h12v04.005.2012346141041.hdf.index': 1528708875,
         'modis/tiles/h12v04/2012337/MOD10A1.A2012337.h12v04.005.2012340033542.hdf.index': 1739917027,
         'modis/tiles/h12v04/2012337/MOD11A1.A2012337.h12v04.005.2012339204007.hdf.index': 640817914,
         'modis/tiles/h12v04/2012337/MOD11A2.A2012337.h12v04.005.2012346152330.hdf.index': 53371709,
         'modis/tiles/h12v04/2012337/MYD10A1.A2012337.h12v04.005.2012340112013.hdf.index': 531935583,
         'modis/tiles/h12v04/2012337/MYD11A1.A2012337.h12v04.005.2012341072847.hdf.index': 1676310978,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MCD_fsnow.tif': 297883486,
-        'modis/tiles/h12v04/2012337/h12v04_2012337_MCD_indices.tif': -2140726827,
+        'modis/tiles/h12v04/2012337/h12v04_2012337_MCD_indices.tif': 1828799894,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MCD_snow.tif': -748640537,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MOD-MYD_obstime.tif': -1729084231,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MOD-MYD_temp.tif': -1718009535,
         'modis/tiles/h12v04/2012337/h12v04_2012337_MOD_clouds.tif': -832284681,
-        'modis/tiles/h12v04/2012337/h12v04_2012337_MOD_ndvi8.tif': -593200294,
         'modis/tiles/h12v04/2012338/MOD10A1.A2012338.h12v04.005.2012341091201.hdf.index': 1725484908,
-        'modis/tiles/h12v04/2012338/MOD11A1.A2012338.h12v04.005.2012341041222.hdf.index': 838676814,
-        'modis/tiles/h12v04/2012338/MYD10A1.A2012338.h12v04.005.2012340142152.hdf.index': -130649785,
-        'modis/tiles/h12v04/2012338/MYD11A1.A2012338.h12v04.005.2012341075802.hdf.index': -642783734,
-        'modis/tiles/h12v04/2012338/h12v04_2012338_MCD_fsnow.tif': -1930181337,
-        'modis/tiles/h12v04/2012338/h12v04_2012338_MCD_snow.tif': 387672365,
-        'modis/tiles/h12v04/2012338/h12v04_2012338_MOD-MYD_obstime.tif': -1693632983,
-        'modis/tiles/h12v04/2012338/h12v04_2012338_MOD-MYD_temp.tif': 1712906003,
-        'modis/tiles/h12v04/2012338/h12v04_2012338_MOD_clouds.tif': 296967275,
     },
 }
```

**Comment by ags-tolson** [comment]
Update:  I spent today trying to figure this out, to no avail.  Commenting out ndvi8 seems to fix the problem for the rest of the products, so per advice from @bhbraswell I'm leaving it that way for the time being.  Apparently ndvi8 is less important as a product so it's okay.

I'll file an issue for this with details on errors observed etc.

**Comment by bhbraswell** [comment]
Now that you know that remove ndvi8 gets rid of the problem, I can look a little more closely at that processing block.

**Comment by ags-tolson** [comment]
@bhbraswell Okay cool, see issue #70 for details I found after our mtg today.  I'm going to pivot back to catching up on system tests now.

**Comment by ags-tolson** [comment]
Tests pass now; I merged in `dev` to this branch since it'd moved and I wanted to make sure some new unit tests passed.

I _think_ this may be ready to merge.

**Comment by bhbraswell** [comment]
I just talked to @justinfisk  about this. There were some questions about whether the update functionality could create a problem for a user who might want to maintain continuity with a thread of work that is an old version. I more or less BSed my way to an agreement with him that for RS data, you either always want the newer version, unless for some reason you don't care about the version.

**Comment by justinfisk** [comment]
I bought the BS. This PR has the coveted fisk seal of approval.

**Comment by ircwaves** [comment]
I believe you mean the "highly coveted"

**Pull request merged**
