### PR TITLE
fetch fix + smallish debugging improvements

### PR DESCRIPTION
**Pull request by ags-tolson**
quick PR as I pivot to RQ; e08a423 is the necessary fetch fix; 0def740 is trying to make life a little easier.

### CODE REVIEW

**Comment by justinfisk** [comment]
So...

I am a bit confused by this PR. I have verified that modis fetch works in the existing batch-scheduler branch without this change. 

Long-term, I think we are going towards a different solution than `requests` based on the EarthData suggested method:
https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python

However, if this fix is necessary outside of my environment, I believe we would have to update merra driver as well.

**Comment by ags-tolson** [comment]
Could it vary by URL & therefore by asset type?  The ones that didn't work for me were MYD10A1 and MOD10A1, which both come from https://n5eil01u.ecs.nsidc.org/.  If you want to try exactly what I did, here's my script:

```from gips.datahandler import api
product_name = "modis_fsnow_fractional-snow-cover"
job_id = api.submit_job('tolson-test-site', product_name,
                                {'tiles': ['h12v04']}, {'dates': '2012-337'})
print "Got a job id: ", job_id
```

Also, modis in dev has been switched over to requests, completely I think, for nine months:

https://github.com/Applied-GeoSolutions/gips/pull/64

I don't know why the query method was written with urllib, or rather, it looks like the query method was written around a very old urllib invocation:

https://github.com/Applied-GeoSolutions/gips/blame/batch-scheduler/gips/data/modis/modis.py#L204

:man_shrugging:

**Comment by justinfisk** [comment]
Interesting. It does fail with fsnow, although the error message is about too many assets rather than auth
```AssertionError: should only be one asset```

**Comment by ags-tolson** [comment]
I think that happened to me too; if so, that line is checking if `len(asset_pile_here) == 1` and when it doesn't get it, it claims too many, but what actually happens is `asset_pile_here` has length 0.

**Comment by ags-tolson** [comment]
oh and the explanation for no auth error is in that issue I filed earlier this week:  https://github.com/Applied-GeoSolutions/gips/issues/238

**Pull request merged**
